# Generated by Django 6.0.7 on 2026-07-17 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A', 'Must / 絶対不可侵'), ('B', 'Should / 努力義務'), ('C', 'Want / 趣味・自己満'), ('D', 'Routine / 裏メニュー')], max_length=1)),
                ('status', models.CharField(choices=[('active', '進行中'), ('zombie', 'ゾンビモード（逆算停止）'), ('archived', 'アーカイブ（ギブアップ）'), ('done', '完了')], default='active', max_length=10)),
                ('unit', models.CharField(default='ページ', max_length=20)),
                ('total_amount', models.PositiveIntegerField()),
                ('completed_amount', models.PositiveIntegerField(default=0)),
                ('actual_deadline', models.DateField(blank=True, null=True)),
                ('margin_days', models.PositiveIntegerField(default=0)),
                ('work_days_per_week', models.PositiveSmallIntegerField(default=7)),
                ('rest_days_remaining', models.PositiveIntegerField(default=0)),
                ('initial_daily_quota', models.FloatField(default=0.0)),
                ('fixed_daily_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('projected_completion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', '-status', 'actual_deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('logical_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_reset_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
