# Generated by Django 5.2.7 on 2026-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='triage_ack_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
